#!/bin/bash

error() {
  echo "ERROR: $1"
  help
  return 1
}

get_core_repos() {
  git clone https://github.com/micropython/micropython/
  git clone http://github.com/espressif/esp-idf
  git clone http://github.com/espressif/esp-homekit-sdk
}

get_espidf_repos() {
  git clone https://github.com/espressif/esptool.git
  git clone https://github.com/espressif/esp32-bt-lib.git
  git clone https://github.com/kmackay/micro-ecc.git
  git clone https://github.com/obgm/libcoap.git
  git clone https://github.com/nghttp2/nghttp2.git
  git clone https://github.com/jedisct1/libsodium.git
  git clone https://github.com/pellepl/spiffs.git
  git clone https://github.com/DaveGamble/cJSON.git
  git clone https://github.com/espressif/mbedtls.git
  git clone https://github.com/espressif/asio.git
  git clone https://github.com/libexpat/libexpat.git
  git clone https://github.com/espressif/esp-lwip.git
  git clone https://github.com/espressif/esp-mqtt.git
  git clone https://github.com/protobuf-c/protobuf-c.git
  git clone https://github.com/ThrowTheSwitch/Unity.git
  git clone https://github.com/leethomason/tinyxml2.git
  git clone https://github.com/espressif/esp-nimble.git
  git clone https://github.com/intel/tinycbor.git
  git clone https://github.com/espressif/esp32-wifi-lib.git
  git clone https://github.com/espressif/tinyusb.git
  git clone https://github.com/espressif/esp-cryptoauthlib.git
  git clone https://github.com/ThrowTheSwitch/CMock.git
  git clone https://github.com/espressif/openthread.git
  git clone https://github.com/espressif/esp32c3-bt-lib.git
}

get_esphk_repos() {
  git clone https://github.com/espressif/json_parser.git
  git clone https://github.com/espressif/json_generator.git
}

repo_fixup() {
  git -C esp-nimble/ checkout nimble-1.2.0-idf  # default branch is nimble-1.3.0-idf, change this
}

_setup-local() {
  if [[ $2 != "" ]]; then  
    if [[ -d $2 ]]; then
      cd "$2" || exit
      get_core_repos
      get_espidf_repos
      get_esphk_repos
      repo_fixup
    else
      error "directory does not exist!"
    fi
  else
    error "no directory specified!"
  fi
}

_espidf-submodules() {
  if [[ $2 != "" ]]; then  
    if [[ -d $2 ]]; then
      cd components/esp-idf || exit
      pwd
      git submodule set-url components/esptool_py/esptool file://"$2"/esptool
      git submodule set-url components/bt/controller/lib file://"$2"/esp32-bt-lib
      git submodule set-url components/bootloader/subproject/components/micro-ecc/micro-ecc file://"$2"/micro-ecc
      git submodule set-url components/coap/libcoap file://"$2"/libcoap
      git submodule set-url components/nghttp/nghttp2 file://"$2"/nghttp2
      git submodule set-url components/libsodium/libsodium file://"$2"/libsodium
      git submodule set-url components/spiffs/spiffs file://"$2"/spiffs
      git submodule set-url components/json/cJSON file://"$2"/cJSON
      git submodule set-url components/mbedtls/mbedtls file://"$2"/mbedtls
      git submodule set-url components/asio/asio file://"$2"/asio
      git submodule set-url components/expat/expat file://"$2"/libexpat
      git submodule set-url components/lwip/lwip file://"$2"/esp-lwip
      git submodule set-url components/mqtt/esp-mqtt file://"$2"/esp-mqtt
      git submodule set-url components/protobuf-c/protobuf-c file://"$2"/protobuf-c
      git submodule set-url components/unity/unity file://"$2"/Unity
      git submodule set-url components/bt/host/nimble/nimble file://"$2"/esp-nimble
      git submodule set-url components/cbor/tinycbor file://"$2"/tinycbor
      git submodule set-url components/esp_wifi/lib file://"$2"/esp32-wifi-lib
      git submodule set-url components/tinyusb/tinyusb file://"$2"/tinyusb
      git submodule set-url  examples/build_system/cmake/import_lib/main/lib/tinyxml2 file://"$2"/tinyxml2
      git submodule set-url examples/peripherals/secure_element/atecc608_ecdsa/components/esp-cryptoauthlib \
                            file://"$2"/esp-cryptoauthlib
    else
      error "directory does not exist!"
    fi
  else
    error "no directory specified!"
  fi
}

_esphk-submodules() {
  if [[ $2 != "" ]]; then  
    if [[ -d $2 ]]; then
      cd components/esp-homekit-sdk || exit
      git submodule set-url components/homekit/json_parser/upstream file://"$2"/json_parser
      git submodule set-url components/homekit/json_generator/upstream file://"$2"/json_generator
    else
      error "directory does not exist!"
    fi
  else
    error "no directory specified!"
  fi
}

help() {
    echo $0
    echo "Commands:"
    echo "  setup-local        <directory>    - Clone micropython-esp32-homekit dependencies to directory"
    echo "  espidf-submodules  <directory>    - Change esp-idf submodule URLs to use local Git directory"
    echo "  esphk-submodules   <directory>    - Change esp-homekit-sdk submodule URLs to use local Git directory"
}

case $1 in
  setup-local) _setup-local "$@";;
  espidf-submodules) _espidf-submodules "$@";;
  esphk-submodules)  _esphk-submodules "$@";;
  help) help;;
  *) help;;
esac